org: xavierdefontaine
app: player-swap-club
# NOTE: update this with your service name
service: player-swap-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: games

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource: "arn:aws:dynamodb:eu-west-2:*:*"

functions:
  create:
    handler: create.main
    events:
      - http:
        path: games
        method: post

  get:
    handler: get.main
    events:
      - http:
        path: games/{id}
        method: get
  
  list:
    handler: list.main
    events:
      - http:
        path: games
        method: get